### ISSUE TITLE
Questions about SAC model and code availability of DAC

### ISSUE THREAD

**Issue by qcxia20** [jkwang93/deepchargepredictor#1]
Hi, I've noticed that DeepChargePredictor has been online these days (http://cadd.zju.edu.cn/deepchargepredictor/). 
That's a great and convenient tool for accurate atomic charge prediction. And I have two questions during using it.
- And here are two more further questions on DeepChargePredictor,
1. The SAC model. I'm wondering that if there is or is going to be a publication on SAC model. I've noticed that SAC was incorporated in DeepChargePredictor server with consideration of molecular 3D information and support on larger molecules compared with DAC. However, there is no other available information like benchmark data or comparison of SAC over other models like DAC to show its accuracy, which may prevent its use. 
2. The code availabilty of DAC. I've noticed that the code of APD and SAC are already available. So I'm curious about whether the code of DAC model will also be shared on github soon.

**Comment by jkwang93** [comment]
Thank you for your interest in our work.
The SAC model is under review and will be published soon. its performance is better than DAC.
The DAC code may be open source in the future.
